In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder  # 범주형 자료 실수화
from sklearn.model_selection import train_test_split    # 학습데이터 나누기
from sklearn.neighbors import KNeighborsClassifier  # knn 불러오기

xy_data = pd.read_csv('iris-train.csv')     # 학습 데이터 가져오기
X_test = pd.read_csv('iris-test.csv')       # 테스트 데이터 가져오기

#문자열 자료 실수화
classle=LabelEncoder()


#학습데이터 X, y
X = xy_data.drop('species', axis=1) # 학습데이터 입력변수 종을 맞춰야 하니까 species에 관한 열을 없애버림.
y = classle.fit_transform(xy_data['species'].values)             # 학습데이터 종속변수
X_train, X_valid, y_train, y_valid = train_test_split(X,y, test_size=0.2, random_state=1, stratify=y) 
print('입력변수(학습데이터)    : ',  X_train.shape)
print('입력변수(검증데이터)  : ', X_valid.shape)
print('종속변수(학습데이터)    : ',  y_train.shape)
print('종속변수(검증데이터)  : ', y_valid.shape)


knn = KNeighborsClassifier(n_neighbors=5, p=1)
knn.fit(X_train, y_train)

y_train_pred = knn.predict(X_train)
y_test_pred = knn.predict(X_test)
print('Misclassified training samples: %d' %(y_train!=y_train_pred).sum()) #학습데이터로 오분류 갯수 확인
print('Misclassified test samples: %d' %(y_valid!=y_test_pred).sum()) #테스트데이터로 오분류 갯수 확인



# classle.inverse_transform(y)  문자열로 다시 복원 이걸 submit에다가 넣어야함.
#print(y)


 





#submit = pd.read_csv("sample_submit.csv")   # 데이터 셋 제출

# submit['species'] = y_test_pred_org
#submit.to_csv("김기환_2019680078_1.csv", mode="w", header = True, index = False)


입력변수(학습데이터)    :  (84, 4)
입력변수(검증데이터)  :  (21, 4)
종속변수(학습데이터)    :  (84,)
종속변수(검증데이터)  :  (21,)
Misclassified training samples: 2


C:\Users\vlrms\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\ipykernel_launcher.py:30: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.


AttributeError: 'bool' object has no attribute 'sum'

In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder  # 범주형 자료 실수화
from sklearn.model_selection import train_test_split

xy_data = pd.read_csv('iris-train.csv')     # 학습 데이터 가져오기
X_test = pd.read_csv('iris-test.csv')       # 테스트 데이터 가져오기


classle=LabelEncoder() #문자열 자료 실수화


#학습데이터 X, y
X = xy_data.drop('species', axis=1) # 학습데이터 입력변수 species열을 drop하고 input X를 정의함
y = classle.fit_transform(xy_data['species'].values)              # 데이터 전처리


X_train,X_valid,y_train,y_valid = train_test_split(X,y, test_size=0.2, random_state=1, stratify=y) 
print('입력변수(학습데이터)    : ',  X_train.shape)
print('입력변수(검증데이터)  : ', X_valid.shape)
print('종속변수(학습데이터)    : ',  y_train.shape)
print('종속변수(검증데이터)  : ', y_valid.shape)    


#knn
from sklearn.neighbors import KNeighborsClassifier  #KNN 불러오기
knn = KNeighborsClassifier(n_neighbors=5, p=2) #5개의 인접한이웃(k를 5로 지정), 거리측정기준:유클리드  /  p2 유클리드. p1 맨해튼
knn.fit(X_train, y_train) #모델 fitting과정

y_train_pred = knn.predict(X_train) #train data의 y값 예측치
y_valid_pred = knn.predict(X_valid)  #모델을 적용한 test data의 y값 예측치
print('Misclassified training samples: %d' %(y_train!=y_train_pred).sum()) #학습데이터로 오분류 갯수 확인
print('Misclassified test samples: %d' %(y_valid!=y_valid_pred).sum()) #테스트데이터로 오분류 갯수 확인

from sklearn.metrics import accuracy_score #정확도 계산을 위한 모듈 import
print(accuracy_score(y_valid,y_valid_pred)) 

from sklearn.metrics import confusion_matrix 
#대각원소가 각각 setosa, versicolor, virginica를 정확하게 분류한 갯수
conf=confusion_matrix(y_true=y_valid,y_pred=y_valid_pred) 
print(conf) #confusion matrix 출력

y_test_pred = knn.predict(X_test)  #모델을 적용한 test data의 y값 예측치
y_test_pred_org = classle.inverse_transform(y_test_pred) #원래의 species 문자열로 복원
submit['species'] = y_test_pred_org
submit.to_csv('김기환_2019680078.csv', mode='w', header= True, index= False) #제출파일 생성

입력변수(학습데이터)    :  (84, 4)
입력변수(검증데이터)  :  (21, 4)
종속변수(학습데이터)    :  (84,)
종속변수(검증데이터)  :  (21,)
Misclassified training samples: 1
Misclassified test samples: 1
0.9523809523809523
[[7 0 0]
 [0 6 1]
 [0 0 7]]


NameError: name 'submit' is not defined

In [ ]:
import pandas as pd

#데이터
xy_data = pd.read_csv('iris-train.csv')
X_test = pd.read_csv('iris-test.csv')

from sklearn.preprocessing import LabelEncoder
import numpy as np

X = xy_data.drop('species', axis=1) #'species'열을 drop하고 input X를 정의함
classle=LabelEncoder() #class label
#'species'열의 문자열을 categorical value로 전환
y=classle.fit_transform(xy_data['species'].values) 
X.shape

from sklearn.model_selection import train_test_split

#X(입력변수)와 y(종속변수)로 이루어진 데이터를 학습과 테스트 데이터넷으로 각각 80%, 20%의 비율로 나눔
X_train,X_valid,y_train,y_valid = train_test_split(X,y, test_size=0.2, random_state=1, stratify=y) 
print('입력변수(학습데이터)    : ',  X_train.shape)
print('입력변수(검증데이터)  : ', X_valid.shape)
print('종속변수(학습데이터)    : ',  y_train.shape)
print('종속변수(검증데이터)  : ', y_valid.shape)

#KNN의 적용
from sklearn.neighbors import KNeighborsClassifier  #KNN 불러오기
knn = KNeighborsClassifier(n_neighbors=5, p=2) #5개의 인접한이웃, 거리측정기준:유클리드
knn.fit(X_train,y_train) #모델 fitting과정
y_train_pred = knn.predict(X_train) #train data의 y값 예측치
y_valid_pred  = knn.predict(X_valid)  #모델을 적용한 test data의 y값 예측치
print('Misclassified training samples: %d' %(y_train!=y_train_pred).sum()) #학습데이터로 오분류 갯수 확인
print('Misclassified test samples: %d' %(y_valid!=y_valid_pred).sum()) #테스트데이터로 오분류 갯수 확인

# 정확도
from sklearn.metrics import accuracy_score #정확도 계산을 위한 모듈 import
print(accuracy_score(y_valid,y_valid_pred))

from sklearn.metrics import confusion_matrix 
#대각원소가 각각 setosa, versicolor, virginica를 정확하게 분류한 갯수
conf=confusion_matrix(y_true=y_valid,y_pred=y_valid_pred) 
print(conf) #confusion matrix 출력

y_test_pred  = knn.predict(X_test)  #모델을 적용한 test data의 y값 예측치
y_test_pred_org = classle.inverse_transform(y_test_pred) #원래의 species 문자열로 복원
submit = pd.read_csv('sample_submit.csv')
submit['species']= y_test_pred_org
submit.to_csv('2019680078.csv', mode='w', header= True, index= False) #제출파일 생성


입력변수(학습데이터)    :  (84, 4)
입력변수(검증데이터)  :  (21, 4)
종속변수(학습데이터)    :  (84,)
종속변수(검증데이터)  :  (21,)
Misclassified training samples: 1
Misclassified test samples: 1
0.9523809523809523
[[7 0 0]
 [0 6 1]
 [0 0 7]]
