In [1]:
import pandas as pd

#데이터
xy_data = pd.read_csv('penguin-train.csv')
X_test = pd.read_csv('penguin-test.csv')

from sklearn.preprocessing import LabelEncoder
import numpy as np

X = xy_data.drop('species', axis=1) #'species'열을 drop하고 input X를 정의함
classle=LabelEncoder() #class label
#'species'열의 문자열을 categorical value로 전환
y=classle.fit_transform(xy_data['species'].values) 
X.shape

from sklearn.model_selection import train_test_split

#확인과정
X_train,X_valid,y_train,y_valid = train_test_split(X,y, test_size=0.3, random_state=1, stratify=y) 
print('입력변수(학습데이터)    : ',  X_train.shape)
print('입력변수(검증데이터)  : ', X_valid.shape)
print('종속변수(학습데이터)    : ',  y_train.shape)
print('종속변수(검증데이터)  : ', y_valid.shape)

#KNN 적용
from sklearn.neighbors import KNeighborsClassifier  #KNN 불러오기
knn = KNeighborsClassifier(n_neighbors=5, p=2) #5개의 인접한이웃, 거리측정기준:유클리드
knn.fit(X_train,y_train) #모델 fitting과정
y_train_pred = knn.predict(X_train) #train data의 y값 예측치
y_valid_pred  = knn.predict(X_valid)  #모델을 적용한 test data의 y값 예측치

# 정확도
from sklearn.metrics import accuracy_score #정확도 계산을 위한 모듈
print(accuracy_score(y_valid, y_valid_pred))

from sklearn.metrics import confusion_matrix 
#대각원소가 각각 Adelie, Gentoo, Chinstrap를 정확하게 분류한 갯수
conf=confusion_matrix(y_true=y_valid, y_pred=y_valid_pred) 
print(conf) #confusion matrix 출력

y_test_pred  = knn.predict(X_test)  #모델을 적용한 test data의 y값 예측치
y_test_pred_org = classle.inverse_transform(y_test_pred) #원래의 species 문자열로 복원
submit = pd.read_csv('sample-submit.csv')
submit['species']= y_test_pred_org
submit.to_csv('2019680078.csv', mode='w', header= True, index= False) #제출파일 생성


입력변수(학습데이터)    :  (186, 4)
입력변수(검증데이터)  :  (81, 4)
종속변수(학습데이터)    :  (186,)
종속변수(검증데이터)  :  (81,)
0.8395061728395061
[[33  0  3]
 [ 7  7  2]
 [ 0  1 28]]
