In [1]:
import numpy as np

quiz_3 = np.array([range(12)], int).reshape(3, 2, 2)
quiz_3

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [2]:
quiz_3[::2]

array([[[ 0,  1],
        [ 2,  3]],

       [[ 8,  9],
        [10, 11]]])

In [11]:
a = np.array(range(1, 7)).reshape(3, -1)
b = np.array(range(1, 7)).reshape(2, -1)
np.dot(a, b)    #행렬의 곱

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

In [6]:
lit = [67, 84, 79, 62, 78, 36, 38, 57, 48, 87, 83, 90, 60, 25, 50, 94, 60, 62, 97, 43]
lit.sort()
print(lit)

[25, 36, 38, 43, 48, 50, 57, 60, 60, 62, 62, 67, 78, 79, 83, 84, 87, 90, 94, 97]
