# 넘파이(NumPy) - 비교 연산과 데이터 추출  

백터와 스칼라값 비교 연산  

In [1]:
import numpy as np
x = np.array([4, 3, 2, 6, 8, 5])
x > 3  # 3 보다 큰 값들만 출력 

array([ True, False, False,  True,  True,  True])

In [2]:
x = np.array([1, 3, 0])     #브로드케스팅으로 x와 y 값을 비교함.
y = np.array([2, 1, 7])
x > y

array([False,  True, False])

In [3]:
x = np.array([4, 6, 7, 3, 2])
(x > 3)

array([ True,  True,  True, False, False])

all() 모든 값이 참일 때 true

In [4]:
(x > 3).all()   

False

any 하나라도 참 일때 true

In [5]:
(x > 3).any()

True

In [6]:
(x < 10).any()

True

In [7]:
(x < 10).all()

True

In [8]:
(x > 10).any()

False

where() 배열이 boolean으로 이루어져 있을 때 참인 값들의 인덱스를 반환 

In [9]:
x = np.array([4, 6, 7, 3, 2])
x > 5      

array([False,  True,  True, False, False])

In [10]:
np.where(x>5)  # x > 5를 만족하는 값은 6과 7  6과 7의 인덱스 값인 [1,2] 반환

(array([1, 2], dtype=int64),)

In [11]:
x = np.array([4, 6, 7, 3, 2])
np.where(x>5 , 10, 20)      # true면 10을 출력 false면 20을 출력

array([20, 10, 10, 20, 20])

In [22]:
x = np.array([4, 6, 7, 3, 2])
np.where(x>5 , 0, 1) # true면 0 false면 1 출력

array([1, 0, 0, 1, 1])

argsort() 작은 순서대로 정렬하여 인덱스 반환  

argmax() 큰 값의 인덱스 반환  

argmin() 가장 작은 값의 인덱스 반환 

In [12]:
x = np.array([4, 6, 7, 3, 2])
np.argsort(x)   #작은 순서대로 정렬하여 인덱스 반환 

array([4, 3, 0, 1, 2], dtype=int64)

In [23]:
np.argmax(x)

2

In [14]:
np.argmin(x)

4

boolean index 배열에 있는 값들을 반환할 특정 조건을 불린형의 배열에 넣어서 추출  
인덱스에 들어가는 배열은 불린형 이어야함.  
불린형 배열과 추출대상이 되는 배열의 구조가 같아야함. 

In [15]:
x = np.array([4, 6, 7, 3, 2])
x > 3       #true인 값만 출력

array([ True,  True,  True, False, False])

In [24]:
cond = x > 3
x[cond] #x가 3이상인 것을 변수 cond에 넣고(마스킹)하고 x를 출력함.

array([4, 6, 7])

In [17]:
x.shape #배열의 구조가 같음.

(5,)

In [18]:
cond.shape  # 배열의 구조가 같음

(5,)

fancy index - 정수형 배열의 값을 사용하여 해당 정수의 인덱스에 위치한 값을 반환  

데이터의 인덱스를 마스킹 함. 

In [19]:
x = np.array([4, 6, 7, 3, 2])
cond = np.array([1, 2, 0, 2, 2, 2,], int)       # 인덱스를 마킹함.
x[cond]     # x에 있는 데이터가 마스킹을 한 값에 따라서 인덱스가 이동함.

array([6, 7, 4, 7, 7, 7])

In [26]:
x.take(cond) # x에 있는 데이터가 마스킹을 한 값에 따라서 인덱스가 이동함.

cond_1 = np.array([1,2,0,4,0,0])
x.take(cond_1)

array([6, 7, 4, 2, 4, 4])

In [31]:
x = np.array([[1,4], [9,16]], int)
x


array([[ 1,  4],
       [ 9, 16]])

In [34]:
a = np.array([0, 1, 1, 1, 0, 0], int)   
b = np.array([0, 0, 0, 1, 1, 1], int)
x[a,b]      # 행렬에도 각각 값을 지정해서 추출 할 수 있음. a는 행 b는 열   

array([ 1,  9,  9, 16,  4,  4])