# 넘파이(NumPy) - 배열 객체 다루기

In [20]:
import numpy as np
test_array = np.array([1, 4, 5, 8], float)  #float 형태로 1차원 배열 생성 
test_array

array([1., 4., 5., 8.])

In [21]:
print(type(test_array[3]))  #내부 인덱스 형식 출력

<class 'numpy.float64'>


In [22]:
test_array = np.array([1, 4, 5, "8"], float)    # str로 넣어도 정의를 실수로 했으므로 float형태.
test_array

array([1., 4., 5., 8.])

In [23]:
type(test_array[3]) # 개별 데이터 타입 역시 실수형 flat64는 64비트 즉 8바이트의 실수형 데이터

numpy.float64

In [24]:
test_array.dtype #배열 전체의 데이터 타입 반환

dtype('float64')

dtype #배열 전체의 데이터 타입 반환

In [25]:
test_array.shape #배열의 구조(shape) 반환

(4,)

shape #배열의 구조(shape) 반환

In [26]:
matrix = [[1,2,5,8], [1,2,5,8], [1,2,5,8]]
np.array(matrix, int).shape

(3, 4)

3 * 4 의 데이터임을 알려줌, shape을 찍어서 출력하면. 앞은 행 뒤 값은 열 이라고 생각하면 됨.

In [27]:
tensor_rank3 = [        # 3차원 텐서
    [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
    [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
    [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
    [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]]
]
np.array(tensor_rank3, int).shape

(4, 3, 4)

원래 있던 행렬의 구조는 뒤로 뒤에 더 있는 행렬은 앞으로. 즉, 4개의 차원이 있고, 각 차원은 3*4의 행렬 구조이다. 

In [28]:
np.array(tensor_rank3, int).ndim    # 차원의 수 

3

In [29]:
np.array(tensor_rank3, int).size    # 넘파이 배열에 있는 모든 데이터의 개수

48

In [30]:
np.array( [ [1, 2, 3.5], [4, 5, 6.5]], dtype=int)

array([[1, 2, 3],
       [4, 5, 6]])

dtype 매개변수 dtype으로 넘파이 배열의 데이터 타입 지정.  
변수가 사용하는 메모리 크기가 정해짐.

In [31]:
np.array([[1, 2, 3.5], [4, 5, 6.5]], dtype=float)

array([[1. , 2. , 3.5],
       [4. , 5. , 6.5]])

float 으로 지정해서 모든 데이터가 실수형으로 저장이됨. 

#itemsize 넘파이 배열에서 각 요소가 차지하는 바이트 확인.#itemsize 넘파이 배열에서 각 요소가 차지하는 바이트 확인.  
32비트, 64 비트로 각각 확인이 가능함.

In [32]:
import sys
np.array([[1, 2, 3.5], [4, 5, 6.5]], dtype=np.int64).itemsize 

8

In [33]:
np.array([[1, 2, 3.5], [4, 5, 6.5]], dtype=np.float64).itemsize

8

itemsize 넘파이 배열에서 각 요소가 차지하는 바이트 확인. 64비트로 확인

In [34]:
np.array( [[1, 2, 3.5], [4, 5, 6.5]], dtype=np.float32).itemsize

4

itemsize 넘파이 배열에서 각 요소가 차지하는 바이트 확인. 32비트호 확인.

In [35]:
x = np.array([[1, 2, 5, 8], [1, 2, 5, 8]])
x.shape

(2, 4)

In [36]:
x.reshape(2,2)  # 행 열이 달라서 안됨. 

ValueError: cannot reshape array of size 8 into shape (2,2)

reshape 배열의 구조를 변경하고 랭크를 조절  


In [ ]:
print(x)
x.reshape(-1,2)

[[1 2 5 8]
 [1 2 5 8]]


array([[1, 2],
       [5, 8],
       [1, 2],
       [5, 8]])

In [ ]:
x.reshape(4,2)  #앞선 구조를 바꿈. 

array([[1, 2],
       [5, 8],
       [1, 2],
       [5, 8]])

In [ ]:
x = np.array(range(8)).reshape(4,2)
x

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

### reshape에 -1 을 사용하면 값을 자동으로 변경 가능. 사용자는 행(row) or 열(colum)중 하나만 명시해주면 됨.

In [ ]:
x.reshape(2,-1)     # 4*2 행렬의 넘파이 배열을 2*4 행렬의 넘파이 배열로 변경. 자동으로 -1 값이 4로 지정됨. 
                    # 행은 2개 만들껀데, 열은 알아서 해줘

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
x

array([[1, 2, 5, 8],
       [1, 2, 5, 8]])

In [ ]:
x.reshape(4,2,-1)   # 랭크가 3인 3차원 텐서가 생성되고 총 8개의 요소가 있으므로 2*2*2의 텐서가 생성됨.
x.ndim

2

In [ ]:
x.reshape(-1,)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
x = np.array(range(8)).reshape(2,2,2)
x

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

### flatten 함수는 데이터 그대로 1차원으로 변경.

In [ ]:
x.flatten()     # 이전에 차원으로 나눠진 것들을 1차원으로 바꿈.

array([0, 1, 2, 3, 4, 5, 6, 7])

### 인덱싱과 슬라이싱  
  
인덱싱 리스트에 있는값의 상대적인 주소로 값에 접근.  

넘파이 배열의 인덱스 표현을 ,을 지원  
  
- [행][열] or [행, 열]  
3차원 텐서 이상은 shape에서 출력되는 랭크 순서대로 인덱싱에 접근

In [ ]:
x = np.array([[1, 2, 3], [4.5, 5, 6]], int)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
x[0][0]

1

In [ ]:
x[0,2]

3

In [ ]:
x[0, 1] = 100       #행 1번째에 2번째 값을 100으로 변경하라. 
x

array([[  1, 100,   3],
       [  4,   5,   6]])

### 연습문제  
3차원 텐서를 생성하고 오랜지색 값을(11을)출력해라.   ppt 사진 

In [38]:
testing = np.array(range(12)).reshape(-1, 2, 2)    #range(12)를 이용해서 0부터 11까지  / 3개 차원, 3개 행, 3개 열
testing

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [ ]:
testing[1,1,0]

6

In [ ]:
testing[2,1,1]  # 3번째에 있는 차원에서 두번째 행, 두 번째 열 값을 출력하라.        # 파이썬은 0 부터

11

In [ ]:
testing[-1, -1, -1]     # 혹은 역순으로 값을 찾음. 

#연습문제 끝 

11

## 인덱싱과 슬라이싱    
  
행과 열을 나눠 각각 슬라이싱 가능.


In [ ]:
x = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], int)
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
x[:,2:] #전체 행의 2열 이상 행 부분은 행 전체, 열 부분은 인덱스가 2 이후의 값
        # 행 전체 열은 2열 이상 모두 인덱싱

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [ ]:
x[1,1:3] #1행의 1열 ~ 2열       행 부분은 첫 번째 행만을 의미. 열부분은 1부터 2까지의 값을 추출
            # 1의 모든 행 선택. 1에서부터 3까지 즉 인덱스 1번째 행에서 인덱스 1,2를 슬라이싱 해 옴.

array([7, 8])

In [ ]:
x[1:3] #1행 ~ 2행의 전체    /     행렬 전체의 열의 개수가 2이기 떄문에 나머지 뒤에는 무시하고 전부 다 가져옴. 

array([[ 6,  7,  8,  9, 10]])

### 연습문제 3차원 텐서에서 4,5 값과 8,9 값을 출력하시오.

In [39]:
testing

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [40]:
testing[1:, 0, 0:2]

array([[4, 5],
       [8, 9]])

In [ ]:
testing[1:, 0, 0:2]  #[1:, 0, :]도 가능.   #0행 의 모든 값
                    # 인덱스 1차원 에서 0번째 행 열은 모두 다 

array([[4, 5],
       [8, 9]])

In [ ]:
testing[0:, 1, 1]

array([ 3,  7, 11])

### 증가값 리스트에서 데이터의 요소를 호출할 떄 데이터를 건너뛰면서 반환.   
[시작 인덱스:마지막 인덱스:증가값]

In [47]:
x = np.array(range(15), int).reshape(3, -1)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [61]:
x[0:2,:2]

array([[0, 1],
       [5, 6]])

In [49]:
x[:, ::2]    #0부터 마지막 인덱스까지 2씩 증가

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14]])

In [ ]:
x[::2,::3]

array([[ 0,  3],
       [10, 13]])

### 연습문제 3

In [ ]:
testing

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [ ]:
testing[::2]        # 행열을 모두 선택하고, 그 선택한 기준으로 2씩 증가. 여기서는 행열이 기준이므로 첫 번째 행렬에서 2를 더한 세번째 행렬이 나옴.

array([[[ 0,  1],
        [ 2,  3]],

       [[ 8,  9],
        [10, 11]]])

## 배열 생성 함수 arange  
range 함수와 같이 차래대로 값을 생성  
(시작 인덱스, 마지막 인덱스, 증가값)  
   
증가값이 실수형이 입력되어도 값을 생성할 수 있음.  
소수점 값을 주기적으로 생성할 때 유용

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(-5, 5)

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [ ]:
np.arange(0, 5, 0.5)    # 실수형이 입력되어도 증가 가능.

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

## ones 함수 1로만 구성된 넘파이 배열을 생성  
## zeros 함수: 0으로만 구성된 넘파이 배열을 생성. 

In [ ]:
np.ones(shape=(5,2), dtype=np.int8) # 5*2 행렬을 생성하고  타입을 8비트로 생성

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int8)

In [ ]:
np.zeros(shape=(2,2), dtype=np.float32)

array([[0., 0.],
       [0., 0.]], dtype=float32)

In [63]:
np.zeros(shape=(5,2), dtype=np.int8)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int8)

empty 활용 가능한 메모리 공간을 확보하여 반환

In [76]:
np.empty(shape=(2,4), dtype=np.float32)

array([[1.4e-45, 2.8e-45, 7.0e-45, 1.1e-44],
       [1.4e-45, 2.8e-45, 7.0e-45, 1.1e-44]], dtype=float32)

In [80]:
x = np.arange(12).reshape(3,2,2)
x.ndim
x.shape
x

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

ones_like 기존 넘파이 배열과 같은 크기로 만들어 내용을 1로 채움  
zeroes_like 기존 넘파이 배열과 같은 크기로 만들어 내용을 0로 채움  
empty_like 기존 넘파이 배열과 같은 크기로 만들어 빈 상태로 만듦

In [81]:
np.ones_like(x)

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [82]:
np.zeros_like(x)

array([[[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]]])

In [83]:
np.empty_like(x)

array([[[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]]])

identity 단위행렬을 생성  
매개변수 n 으로 n*n 단위 행렬을 생성 

In [84]:
np.identity(n=3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [86]:
np.identity(n=4, dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

eye 시작점과 행렬 크기를 지정, 단위행렬 생성      

N은 행의 개수, M은 열의 개수  
k는 열의 값을 기준으로 시작 인덱스 

In [ ]:
np.eye(N=3, M=5) 

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [ ]:
np.eye(N=3, M=5, k=2)   # k 열의 값을 기준으로 시작 인덱스 k가 2 이므로 인덱스 2에서 단위행렬을 만듬

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

diag 행렬의 대각성분 값을 추출  
k는 열의 값을 기준으로 시작 인덱스

In [87]:
matrix = np.arange(9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [88]:
np.diag(matrix) # 대각선인 0,4,8 값을 가져 옴.

array([0, 4, 8])

In [89]:
np.diag(matrix, k=1)    # k는 열의 값을 기준으로 

array([1, 5])

uniform 균등분포 함수  
np.random.uniform(시작값, 끝값, 데이터개수)  
normal 함수 정규분포함수 (평군값, 분산, 데이터개수)

In [90]:
np.random.uniform(0, 5, 10)

array([2.75400186, 4.97405351, 0.78962122, 2.29251334, 2.20771551,
       2.69428562, 1.21327866, 3.54992483, 1.63443191, 2.76444041])

In [91]:
np.random.normal(0, 2, 10)

array([-3.74280888,  0.74580888,  3.18937634, -0.53678969,  1.8936091 ,
        0.88350897, -1.89421204, -2.41890041,  1.61360507,  0.01010495])