# 넘파이(NumPy) - 배열 연산

In [1]:
import numpy as np
test_array = np.arange(1, 11) #1부터 10까지의 함수 생성
test_array.sum()    # 1부터 10까지 모두 더한 값

55

In [2]:
test_array = np.arange(1,13).reshape(3,4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

axis 0 열/  axis 1 행

In [3]:
test_array.sum(axis=0)      # 열 방향으로 더한 값

array([15, 18, 21, 24])

In [4]:
test_array.sum(axis=1)  # 행 방향으로 더한 값

array([10, 26, 42])

### 3차원 텐서에서는 어케 할까?  
  
3차원에서는   
axis = 0은 차원   
axis = 1은 열  
axis = 2는 행  


In [43]:
test_array = np.arange(1, 13).reshape(3, 4)
third_order_tensor = np.array([test_array, test_array, test_array])
third_order_tensor

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [6]:
third_order_tensor.sum(axis=0)  # 차원마다 더하기 

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36]])

In [7]:
third_order_tensor.sum(axis=1)  # 열 마다 더하기 

array([[15, 18, 21, 24],
       [15, 18, 21, 24],
       [15, 18, 21, 24]])

In [44]:
third_order_tensor.sum(axis=2)  # 행 마다 더하기    

array([[10, 26, 42],
       [10, 26, 42],
       [10, 26, 42]])

연산함수  mean(평균), std(표준편차 연산), sqrt(제곱근 연산)  
  
연산 함수:배열 내부 연산을 지원하는 함수

In [46]:
test_array = np.arange(1, 13).reshape(3, 4) 
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
test_array.mean(axis=1) #axis=1  축을(행) 기준으로 평균 연산. mean 평균 

array([ 2.5,  6.5, 10.5])

In [10]:
test_array.std() #전체 값에 대한 표준편차 연산  

3.452052529534663

In [11]:
test_array.std(axis=0) #axis=0 축을(열) 기준으로 표준편차 연산

array([3.26598632, 3.26598632, 3.26598632, 3.26598632])

In [51]:
np.sqrt(test_array) #각 요소에 제곱근 연산 수행

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479, 3.46410162]])

AttributeError: 'numpy.ndarray' object has no attribute 'sqrt'

### 연결함수  
vstack 수직으로 붙여 하나의 행렬 생성  
hstack 수평으로 하나의 행렬 생성

In [59]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
np.vstack((v1, v2)) # 수직으로 붙여서 하나의 행렬 생성

array([[1, 2, 3],
       [4, 5, 6]])

In [61]:
np.hstack((v1,v2))  # 수평으로 붙여서 하나의 행렬 생성

array([1, 2, 3, 4, 5, 6])

In [62]:
v1 = v1.reshape(-1, 1) #v1 = np.array([1, 2, 3])
v2 = v2.reshape(-1, 1) #v2 = np.array([4, 5, 6])
v1

array([[1],
       [2],
       [3]])

In [63]:
v2

array([[4],
       [5],
       [6]])

In [64]:
np.hstack((v1,v2))  #v1, v2를 수평으로 행렬을 만듦. [1][4] 는 각각의 행렬에서 동일한 위치이기 때문에 [1,4]가 수평으로 붙음.  다른 행렬도 마찬가지

array([[1, 4],
       [2, 5],
       [3, 6]])

In [65]:
np.vstack((v1,v2)) #v1, v2를 수직으로 행렬을 만듦. [1][4] 는 각각의 행렬에서 동일한 위치이기 때문에 [1], [2]가 수직으로 붙음.  다른 행렬도 마찬가지

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

concatenate 함수 축을 고려하여 두 개의 배열을 결합  
앞선 스택 계열의 함수와는 달리 생성될 배열과 소스가 되는 배열의 축방향 차원이 같아야함.   
두벡터를 결합하고 싶다면, 해당 벡터를 일단 2차원 배열 꼴로 변환 후 행렬로 나타내야 함.

In [72]:
v1 = np.array([[1, 2, 3]])
v2 = np.array([[4, 5, 6]])
v3 = np.concatenate((v1,v2), axis=0) # 열 방향
v3

array([[1, 2, 3],
       [4, 5, 6]])

In [77]:
v1 = np.array([[1, 2, 3]])
v2 = np.array([[4, 5, 6]])
np.concatenate((v1,v2), axis=1) # 행 방향

array([[1, 2, 3, 4, 5, 6]])

In [78]:
v1 = np.array([1, 2, 3, 4]).reshape(2,2)
v1

array([[1, 2],
       [3, 4]])

In [79]:
v2 = np.array([[5,6]]).T    # .T 전치 / np.transpose(대상_변수)   / np.swqpaxws(변수, axis(0 or 1), axis(0 or 1))
v2

array([[5],
       [6]])

In [83]:
np.concatenate((v1,v2), axis=1) #axis 1은 행 / 0은 열

array([[1, 2, 5],
       [3, 4, 6]])

In [84]:
np.concatenate((v1,v2), axis=0) #축 방향 차원이 달라서 안됨. v1이 축 방향에 더 많아서 안됨

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 1

### 넘파이 사칙연산  
같은 배열의 구조일 때 요소별 연산이 가능하다.

In [23]:
x = np.arange(1, 7).reshape(2,3)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
x + x

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [25]:
x - x

array([[0, 0, 0],
       [0, 0, 0]])

In [26]:
x / x

array([[1., 1., 1.],
       [1., 1., 1.]])

In [27]:
x ** x

array([[    1,     4,    27],
       [  256,  3125, 46656]], dtype=int32)

배열 간의 곱셈 m*n n*l 행렬 내적하면 m*l 행렬 생성  
행렬의 곱셈 연산 .dot()

In [28]:
x_1 = np.arange(1, 7).reshape(2,3)
x_1

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
x_2 = np.arange(1, 7).reshape(3,2)
x_2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [85]:
x_1.dot(x_2)    #dot 벡터의 곱셈 연산 가능

array([[22, 28],
       [49, 64]])

브로드캐스팅 연산: 하나의 행렬과 스칼라 값들 간의 연산이나 행렬과 백터 간의 연산

In [31]:
x = np.arange(1, 10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [86]:
x + 10 

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19],
       [20, 21, 22]])

In [33]:
x - 2

array([[-1,  0,  1],
       [ 2,  3,  4],
       [ 5,  6,  7]])

In [34]:
x // 3

array([[0, 0, 1],
       [1, 1, 2],
       [2, 2, 3]], dtype=int32)

In [35]:
x ** 2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]], dtype=int32)

행렬과 벡터, 벡터와 백터 간에도 연산이 가능함. 브로트케스트 기능 

In [36]:
x = np.arange(1, 13).reshape(4,3)
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [37]:
v = np.arange(10 , 40 , 10)
v

array([10, 20, 30])

In [38]:
x + v

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39],
       [20, 31, 42]])

# 퀴즈  
백터와 벡터 간의 덧셈을 브로트캐스팅 연산을 이용하여 코드를 작성하시오. 

In [87]:
x1 = np.arange(1, 4, 1)
x1

array([1, 2, 3])

In [40]:
v1 = np.arange(1, 4, 1).reshape(-1, 1)  #reshape(3,1)
v1

array([[1],
       [2],
       [3]])

In [41]:
result = x1 + v1

result



array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [2]:
import  numpy as np

a = np.arange(6).reshape(2,3)

b = a > 4
a[b]

array([5])